var guitars = [
  {
    _id: "1",
    name: "American Standard Stratocaster",
    color: "3 Color Sunburst",
    image: "/images/strat.jpg",
    brand: "Fender",
    category: "Blues",
    price: "1,10,000",
    countInStock: 15,
    rating: 4.5,
    numReviews: 25,
  },
  {
    _id: "2",
    name: "Les Paul SG - AC/DC Edition",
    color: "Ebony",
    image: "/images/sg-ebony.jpg",
    brand: "Gibson",
    category: "Rock",
    price: "99,000",
    countInStock: 9,
    rating: 4.0,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Les Paul Standard - Slash Edition",
    color: "Vintage Sunburst",
    image: "/images/les-paul-standard.jpg",
    brand: "Gibson",
    category: "Rock",
    price: "1,40,000",
    countInStock: 5,
    rating: 5,
    numReviews: 22,
  },
  {
    _id: "4",
    name: "Custom 24 - John Mayer Edition",
    color: "Lush Green",
    image: "/images/custom-24.png",
    brand: "PRS",
    category: "Blues",
    price: "1,05,000",
    countInStock: 5,
    rating: 2.5,
    numReviews: 34,
  },
  {
    _id: "5",
    name: "325 Rickenbacker 1969 Custom",
    color: "Panther Black",
    image: "/images/325-rickenbacker.png",
    brand: "Rickenbacker",
    category: "Jingle Jangle",
    price: "2,10,000",
    countInStock: 0,
    rating: 3.5,
    numReviews: 7,
  },
  {
    _id: "6",
    name: "American Standard Telecaster",
    color: "Custom Old Wood",
    image: "/images/telecaster.png",
    brand: "Fender",
    category: "Blues",
    price: "1,10,000",
    countInStock: 1,
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "7",
    name: "100 Series Acoustic Special Edition",
    color: "Vintage Natural Dark",
    image: "/images/100-series-acoustic.jpg",
    brand: "Taylor",
    category: "All",
    price: "60,000",
    countInStock: 7,
    rating: 4.0,
    numReviews: 9,
  },
];

module.exports.guitars = guitars;
